optimizable_params:
    # - /arm_controller/gains/elbow_joint/d
    # - /arm_controller/gains/elbow_joint/i
    # - /arm_controller/gains/elbow_joint/p

    # - /arm_controller/gains/shoulder_lift_joint/d
    # - /arm_controller/gains/shoulder_lift_joint/i
    # - /arm_controller/gains/shoulder_lift_joint/p
    
    # - /arm_controller/gains/shoulder_pan_joint/d
    # - /arm_controller/gains/shoulder_pan_joint/i
    # - /arm_controller/gains/shoulder_pan_joint/p
    
    # - /arm_controller/gains/wrist_1_joint/d
    # - /arm_controller/gains/wrist_1_joint/i
    # - /arm_controller/gains/wrist_1_joint/p
    
    # - /arm_controller/gains/wrist_2_joint/d
    # - /arm_controller/gains/wrist_2_joint/i
    # - /arm_controller/gains/wrist_2_joint/p
    
    # - /arm_controller/gains/wrist_3_joint/d
    # - /arm_controller/gains/wrist_3_joint/i
    # - /arm_controller/gains/wrist_3_joint/p

    # - /ddynrec/robot___elbow_joint___damping
    # - /ddynrec/robot___elbow_joint___friction
    # - /ddynrec/robot___shoulder_lift_joint___damping
    # - /ddynrec/robot___shoulder_lift_joint___friction
    # - /ddynrec/robot___shoulder_pan_joint___damping
    # - /ddynrec/robot___shoulder_pan_joint___friction
    # - /ddynrec/robot___world_joint___damping
    # - /ddynrec/robot___world_joint___friction
    # - /ddynrec/robot___wrist_1_joint___damping
    # - /ddynrec/robot___wrist_1_joint___friction
    # - /ddynrec/robot___wrist_2_joint___damping
    # - /ddynrec/robot___wrist_2_joint___friction
    # - /ddynrec/robot___wrist_3_joint___damping
    # - /ddynrec/robot___wrist_3_joint___friction

    
    - /luke_left_hand_description/wrist_rot/damping
    - /luke_left_hand_description/wrist_rot/friction

    - /luke_left_hand_description/thumb_yaw/damping
    - /luke_left_hand_description/thumb_yaw/friction

    - /luke_left_hand_description/index_proximal_flex/damping
    - /luke_left_hand_description/index_proximal_flex/friction

    - /luke_left_hand_description/wrist_flex/damping
    - /luke_left_hand_description/wrist_flex/friction

    - /luke_left_hand_description/thumb_pitch/damping
    - /luke_left_hand_description/thumb_pitch/friction

    - /luke_left_hand_description/mrp_differential_flex/damping
    - /luke_left_hand_description/mrp_differential_flex/friction

    # - /luke_left_hand_description/elbow/damping
    # - /luke_left_hand_description/elbow/friction
    # - /luke_left_hand_description/index_distal_flex/damping
    # - /luke_left_hand_description/index_distal_flex/friction
    # - /luke_left_hand_description/index_proximal_flex/damping
    # - /luke_left_hand_description/index_proximal_flex/friction
    # - /luke_left_hand_description/middle_distal_flex/damping
    # - /luke_left_hand_description/middle_distal_flex/friction
    # - /luke_left_hand_description/middle_median_flex/damping
    # - /luke_left_hand_description/middle_median_flex/friction
    # - /luke_left_hand_description/middle_proximal_flex/damping
    # - /luke_left_hand_description/middle_proximal_flex/friction
    # - /luke_left_hand_description/mrp_differential_flex/damping
    # - /luke_left_hand_description/mrp_differential_flex/friction
    # - /luke_left_hand_description/pinky_distal_flex/damping
    # - /luke_left_hand_description/pinky_distal_flex/friction
    # - /luke_left_hand_description/pinky_proximal_flex/damping
    # - /luke_left_hand_description/pinky_proximal_flex/friction
    # - /luke_left_hand_description/ring_distal_flex/damping
    # - /luke_left_hand_description/ring_distal_flex/friction
    # - /luke_left_hand_description/ring_median_flex/damping
    # - /luke_left_hand_description/ring_median_flex/friction
    # - /luke_left_hand_description/ring_proximal_flex/damping
    # - /luke_left_hand_description/ring_proximal_flex/friction
    # - /luke_left_hand_description/thumb_pitch/damping
    # - /luke_left_hand_description/thumb_pitch/friction
    # - /luke_left_hand_description/thumb_yaw/damping
    # - /luke_left_hand_description/thumb_yaw/friction
    # - /luke_left_hand_description/wrist_ab_ad/damping
    # - /luke_left_hand_description/wrist_ab_ad/friction
    # - /luke_left_hand_description/wrist_flex/damping
    # - /luke_left_hand_description/wrist_flex/friction
    # - /luke_left_hand_description/wrist_rot/damping
    # - /luke_left_hand_description/wrist_rot/friction